[Theme]
Current=breeze

[Autologin]
# Autologin in live session only — disabled for installed system
# User=mint
# Session=plasma

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on

[Users]
MaximumUid=65000
MinimumUid=1000
