title   Mint OS Live
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/intel-ucode.img
initrd  /arch/boot/amd-ucode.img
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archisolabel=MINTOS quiet splash loglevel=3 rd.udev.log_priority=3 vt.global_cursor_default=0
