title   Mint OS Live (Safe Mode)
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/intel-ucode.img
initrd  /arch/boot/amd-ucode.img
initrd  /arch/boot/x86_64/initramfs-linux-fallback.img
options archisobasedir=arch archisolabel=MINTOS nomodeset
