# =============================================================================
# Mint OS — Calamares Installer Configuration
# =============================================================================

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:       online
  module:   welcome
  config:   welcome.conf
- id:       before
  module:   shellprocess
  config:   shellprocess_before.conf
- id:       after
  module:   shellprocess
  config:   shellprocess_after.conf

sequence:
- show:
  - welcome@online
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@before
  - grubcfg
  - bootloader
  - shellprocess@after
  - umount
- show:
  - finished

branding: mintos

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
