[connection]
# Randomize MAC address on Ethernet connections for privacy
ethernet.cloned-mac-address=random
# Randomize WiFi MAC per network
wifi.cloned-mac-address=stable

[device]
wifi.backend=iwd
wifi.scan-rand-mac-address=yes
wifi.iwd.autoconnect=yes

[main]
dns=systemd-resolved
systemd-resolved=false

[connectivity]
uri=https://archlinux.org/
interval=300
