---
# Mint OS — Partition Configuration

efiSystemPartition:         /boot/efi
efiSystemPartitionSize:     512
efiSystemPartitionName:     EFI

swapPartitionName:          swap

defaultFileSystemType:      btrfs
availableFileSystemTypes:
    - btrfs
    - ext4
    - xfs

ensureSuspendToDisk:        true
neverCreateSwapPartition:   false
requiredStorage:            20

defaultPartitionTableType:  gpt

luksGeneration:             luks2

allowManualPartitioning:    true
initialPartitioningChoice:  erase
initialSwapChoice:          suspend

drawNestedPartitions:       true
alwaysShowPartitionLabels:  true
