---
# Mint OS — Users Configuration

userShell: /usr/bin/zsh

defaultGroups:
    - wheel
    - audio
    - video
    - optical
    - storage
    - docker
    - network
    - lp
    - scanner

autologinGroup: autologin

doAutologin: false

sudoersGroup: wheel

setRootPassword: true

passwordRequirements:
    minLength: 6
    maxLength: 256
    libpwquality:
        - try_first_pass
        - local_users_only
        - minlen=6
        - minclass=1

allowWeakPasswords: false

presets:
    fullName: ""
    loginName: ""
    userPassword: ""
    rootPassword: ""
    isSamePasswordForRoot: true
    autoLogin: false
