---
# Mint OS — Calamares Welcome Module

showSupportUrl:            true
showKnownIssuesUrl:        true
showReleaseNotesUrl:       false
showDonateUrl:             false

requirements:
    requiredStorage:       20
    requiredRam:           2.0
    internetCheckUrl:      https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
