# Mint OS — Kernel Module Configuration

# zram
options zram num_devices=1

# Bluetooth power saving
options btusb enable_autosuspend=n

# Disable PC speaker beep
blacklist pcspkr
blacklist snd_pcsp

# Watchdog — disable for faster boot
blacklist iTCO_wdt
blacklist iTCO_vendor_support

# NTFS3 kernel driver (faster than ntfs-3g)
options ntfs3 nls=utf8 prealloc
