# Mint OS - security limits
# Needed for some security testing tools

* soft nofile 65535
* hard nofile 65535
* soft nproc  65535
* hard nproc  65535

# Allow large core dumps for debugging/forensics
* soft core unlimited
